apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchainsvc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchainsvc
  template:
    metadata:
      labels:
        app: blockchainsvc
    spec:
      containers:
      - name: blockchainsvc
        image: candidate/blockchainsvc:latest
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blockchainsvc-service
spec:
  selector:
    app: blockchainsvc
  ports:
    - name: http
      port: 80
      targetPort: 7777
      protocol: TCP
